import _ from 'lodash';
import {
    FETCH_STREAM,
    FETCH_STREAMS,
    CREATE_STREAM,
    EDIT_STREAM,
    DELETE_STREAM
} from '../actions/types';

export default (state = {}, action) => {
    switch (action.type) {
        case FETCH_STREAMS:
            // lodash mapKeys is a function that takes an array and a function as arguments. It returns a new object with the keys generated by the function.
            return { ...state, ..._.mapKeys(action.payload, 'id') };
        case FETCH_STREAM:
            // const NewState = { ...state };
            // NewState[action.payload.id] = action.payload;
            // return NewState; 
            return { ...state, [action.payload.id]: action.payload }; // ES6 syntax for above. adds to state and replace if same key
        case CREATE_STREAM:
            return { ...state, [action.payload.id]: action.payload };
        case EDIT_STREAM:
            return { ...state, [action.payload.id]: action.payload };
        case DELETE_STREAM:
            return _.omit(state, action.payload);
        default:
            return state;
    }
};